# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

frameworkVersion: "=3.30.1"

plugins:
  - serverless-webpack

# TODO Set up custom domain via serverless, see https://www.serverless.com/blog/serverless-api-gateway-domain/ and https://www.npmjs.com/package/serverless-domain-manager

# The `service` block is the name of the service
service: cryfs-web-backend

custom:
  webpack:
    includeModules: true # enable auto-packing of external modules

package:
  individually: true

# TODO This is likely the default and can be removed in serverless v4
configValidationMode: error

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
      - Effect: 'Allow'
        Action: 'ssm:GetParameters'
        Resource:
          - 'arn:aws:ssm:us-east-1:171839190218:parameter/MAILCHIMP_API_TOKEN'
          - 'arn:aws:ssm:us-east-1:171839190218:parameter/MAILCHIMP_LIST_ID'
          - 'arn:aws:ssm:us-east-1:171839190218:parameter/SENDGRID_API_KEY'


# The `functions` block defines what code to deploy
functions:
  newsletterRegister:
    handler: newsletter.register
    events:
      - http:
          path: newsletter/register
          method: post
          cors: true
  contactSend:
    handler: contact.send
    events:
      - http:
          path: contact/send
          method: post
          cors: true
