# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

frameworkVersion: "=1.41.1"

plugins:
  - serverless-webpack

# The `service` block is the name of the service
service: cryfs-web-backend

custom:
  webpack:
    includeModules: true # enable auto-packing of external modules

package:
  individually: true

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: 'Allow'
      Action: 'ssm:GetParameters'
      Resource:
        - 'arn:aws:ssm:us-east-1:171839190218:parameter/MAILCHIMP_API_TOKEN'
        - 'arn:aws:ssm:us-east-1:171839190218:parameter/MAILCHIMP_LIST_ID'
        - 'arn:aws:ssm:us-east-1:171839190218:parameter/SENDGRID_API_KEY'


# The `functions` block defines what code to deploy
functions:
  newsletterRegister:
    handler: newsletter.register
    events:
      - http:
          path: newsletter/register
          # TODO Post
          method: get
          # TODO Restrict cors to requests coming from cryfs.org see https://serverless.com/framework/docs/providers/aws/events/apigateway/#simple-http-endpoint
          cors:
            origin: 'next.cryfs.org'
            allowCredentials: false
  contactSend:
    handler: contact.send
    events:
      - http:
          path: contact/send
          method: post
          # TODO Restrict cors to requests coming from cryfs.org see https://serverless.com/framework/docs/providers/aws/events/apigateway/#simple-http-endpoint
          cors:
            origin: 'next.cryfs.org'
            allowCredentials: false
