version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:11.12.0

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Update Npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: 'npm run build'
      - run:
          name: Export
          command: 'npm run export'
      - run:
          name: Copy to Workspace
          command: |
            mkdir -p /tmp/workspace
            rm -rf /tmp/workspace/out
            mv out /tmp/workspace
            mkdir /tmp/workspace/out/.circleci
            cp .circleci/config.dummy.yml /tmp/workspace/out/.circleci/config.yml
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - out

  deploy:
    executor: my-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8f:bc:a3:32:67:e8:39:b5:35:1c:45:16:3a:7b:7b:e1"
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Setup Git
          command: |
            git config user.email "messmer@cryfs.org"
            git config user.name "Circle CI Deployment"
            git checkout gh-pages
      - run:
          # Delete all files except the 'CNAME' file (which configures custom domains for github pages)
          name: Delete Old Version
          command: |
            git rm -r --ignore-unmatch *
            git reset HEAD CNAME
            git checkout CNAME
      - run:
          name: Replace with New Version
          command: |
            cp -R /tmp/workspace/out/. .
            git add .
            find .
            git status
      - run:
          name: Commit Changes
          command: |
            git commit -m "Update to ${CIRCLE_SHA1}"
            git status
      - run:
          name: Push to GitHub Pages
          command: |
            git push


workflows:
  version: 2

  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
